### ISSUE TITLE
Fire Dragons spawining in Lightning Dragon biomes

### ISSUE THREAD

**Issue by AppleBurst** [IAFEnvoy/IceAndFire-CE#4]
just a little thing I noticed, it's not a big bug in the slightest, but it's just a bit annoying. I was running around some savanna/jungle biomes and noticed not only lightning nests but fire nests too. It probably has something to do with fire dragons spawning in warm biomes, which are also the habitats of lightning dragons. Once again, not a big problem, just a little inconsistency.

**Comment by IAFEnvoy** [comment]
This is a problem related to biome tags, and you can adjust by yourself.

**Comment by IAFEnvoy** [comment]
In newest version i use a vanilla setting which can keep them out of at least 6 chunks, so i think they will not generate too often now.
